image:
    - Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017

environment:
  matrix:
    - PYTHON: C:\Python27-x64


# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\GFF3toolkit

platform: x64

configuration: Release

install:
  - pip install wheel
  - cd c:\projects\GFF3toolkit
  - pip install .

build: off

test_script:
  - gff3_QC -g example_file/example.gff3 -f example_file/reference.fa -o error.txt
  - gff3_fix -qc_r error.txt -g example_file/example.gff3 -og corrected.gff3
  - gff3_merge -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt
  - gff3_merge -g1 example_file/new_models_w_replace.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt -noAuto
  - gff3_sort -g example_file/example.gff3 -og example-sorted.gff3
  - ps: Write-Host "Test scripts are finished ..."

deploy: false

