sudo: required

matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    install:
      - pip install .
  - os: linux
    language: python
    python: 2.7
    install:
      - pip install gff3tool --no-cache
  - os: osx
    language: generic
    install:
      - pip2 install .
  - os: osx
    language: generic
    install:
      - pip2 install gff3tool --no-cache

script:
  - gff3_QC -g example_file/example.gff3 -f example_file/reference.fa -o error.txt
  - gff3_fix -qc_r error.txt -g example_file/example.gff3 -og corrected.gff3
  - gff3_merge -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt
  - gff3_merge -g1 example_file/new_models_w_replace.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt -noAuto
  - gff3_sort -g example_file/example.gff3 -og example-sorted.gff3
  - gff3_to_fasta -g example_file/example.gff3 -f example_file/reference.fa -st all -d simple -o test_sequences
