sudo: required

matrix:
  include:
  - os: linux
    language: python
    python: 3.7
    install:
      - pip3 install .
  - os: osx
    language: generic
    python: 3.7
    install:
      - pip3 install .
  - os: osx
    language: generic
    python: 3.7
    install:
      - pip3 install .
  - os: linux
    language: ruby
    python: 3.7
    rvm: 2.2
    before_script: gem install awesome_bot
    script: awesome_bot --allow-redirect --allow-dupe README.md docs/*.md # only this instance will check the documents

install:
  - pip install --user coveralls coverage codecov

script:
  - coverage run gff3tool/bin/gff3_QC.py -g example_file/example.gff3 -f example_file/reference.fa -o error.txt
  - coverage run gff3tool/bin/gff3_fix.py -qc_r error.txt -g example_file/example.gff3 -og corrected.gff3
  - coverage run gff3tool/bin/gff3_merge.py -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt
  - coverage run gff3tool/bin/gff3_merge.py -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -u1 example_file/u1.txt -u2 example_file/u2.txt -r merged_report.txt
  - coverage run gff3tool/bin/gff3_merge.py -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -u1 example_file/u1.txt -r merged_report.txt
  - coverage run gff3tool/gff3_merge.py -g1 example_file/new_models.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -u2 example_file/u2.txt -r merged_report.txt
  - coverage run gff3tool/bin/gff3_merge.py -g1 example_file/new_models_w_replace.gff3 -g2 example_file/reference.gff3 -f example_file/reference.fa -og merged.gff -r merged_report.txt -noAuto
  - coverage run gff3tool/bin/gff3_sort.py -g example_file/example.gff3 -og example-sorted.gff3
  - coverage run gff3tool/bin/gff3_to_fasta.py -g example_file/example.gff3 -f example_file/reference.fa -st all -d simple -o test_sequences
  
after_success:
  - coverage report
  - coveralls
  - codecov
